image:
  name: andreasdog/corda-client-springboot:0.1.0
  pullPolicy: Always

enabled: true

service:
  port: 10050
  type: ClusterIP

client:
  tradelens:
    apikey: ""
    orgId: ""

ingress:
  enabled: false
  host: corda-client-api.local

configmap:
  server:
    port: 10050
  config:
    rpc:
      host: corda
      port: 10006
      username: user1 
      password: vzzuABeCut3jGoJfEp94
