image:
  name: federatedbdi/bdi-api:0.3.9
  pullPolicy: IfNotPresent

enabled: true

service:
  port: 10050
  type: ClusterIP

client:
  graphdb:
    host: namespace-graphdb
    port: 7200
    repository: bdi

ingress:
  enabled: false
  host: corda-client-api.local

configmap:
  server:
    port: 10050
  corda:
    rpc:
      host: corda
      port: 10006
      username: user1 
      password: vzzuABeCut3jGoJfEp94
  graphdb:
    sparql:
      url: http://localhost:7200/repositories/bdi
  bdi:
    event:
      distribution:
        rules:
          # options: broadcast, static
          list: broadcast
          #static:
            # Comma separated list of static destinations, all events will be sent to the locations specified here.
            #destinations: DCA/Schiphol/NL