{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corda-client-api.fullname" . }}
  labels:
    {{- include "corda-client-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "corda-client-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "corda-client-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ template "corda-client-api.fullname" $ }}-config
          configMap:
            name: {{ template "corda-client-api.fullname" $ }}-config
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}
          volumeMounts:
            - name: {{ template "corda-client-api.fullname" $ }}-config
              mountPath: /opt/api/config
          args:
            - /bin/bash
            - -c
            - java --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -Dspring.config.additional-location=file:/opt/api/config/ -Dserver.port=$springPort -Dcorda.rpc.host=$cordaHost -Dcorda.rpc.port=$cordaPort -Dcorda.rpc.username=$cordaUser -Dcorda.rpc.password=$cordaPassword -Dgraphdb.sparql.url=$graphdbSparqlUrl -Dbdi.event.distribution.rules.list=$bdiEventDistributionRulesList -Dbdi.event.distribution.rules.static.destinations=$bdiEventDistributionRulesStaticDestinations -jar api.jar
          env:
            - name: JDK_JAVA_OPTIONS
              value: "--add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED"
            - name: cordaHost
              value: "{{ .Release.Name }}-corda-node"
            - name: cordaPort
              value: "{{ .Values.configmap.corda.rpc.port }}"
            - name: cordaUser
              value: {{ .Values.configmap.corda.rpc.username }}
            - name: cordaPassword
              value: {{ .Values.configmap.corda.rpc.password }}
            - name: springPort
              value: "{{ .Values.configmap.server.port }}"
            - name: graphdbSparqlUrl
              value: "http://{{ .Release.Name }}-graphdb:7200/repositories/bdi"
            - name: bdiEventDistributionRulesList
              value: "{{ .Values.configmap.bdi.event.distribution.rules.list }}"
            {{- if ((.Values.configmap.bdi.event.distribution.rules.static).destinations) }}
            - name: bdiEventDistributionRulesStaticDestinations
              value: "{{ .Values.configmap.bdi.event.distribution.rules.static.destinations }}"
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.configmap.server.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{ end -}}