{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "corda-client-api.labels" . | nindent 4 }}
  name: {{ include "corda-client-api.fullname" . }}
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Release.Name }}.k8s.basicdatasharinginfrastructure.net
      secretName: {{ include "corda-client-api.fullname" . }}-tls
  rules:
  - host: {{ .Release.Name }}.k8s.basicdatasharinginfrastructure.net
    http:
      paths:
      - path: /
        # rewriteTarget: /$1
        pathType: Prefix
        backend:
          service:
            name: {{ include "corda-client-api.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{ end -}}