apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "corda-client-api.fullname" $ }}-config
data:
  database.properties: |-
    tradelens.apikey={{ .Values.client.tradelens.apikey }}
    tradelens.orgId={{ .Values.client.tradelens.orgId }}