
federated-corda-node:

  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: corda-k8s # Replace with the resource group of the Azure Kubernetes cluster

  service:
    type: LoadBalancer
    loadBalancerIP: 20.31.101.154 # Replace with pre-instantiated Azure Public IP Address

  p2pPort: 10008
  rpcPort: 10009
  p2pAddress: 20.31.101.154

  myLegalName: OU=Node2,O=Demo,L=Utrecht,C=NL

federated-node-api:
  configmap:
    federated:
      node:
        corda:
          rpc:
            port: 10009
        event:
          distribution:
            rules:
              list: static
              static:
                destinations: OU=Node1,O=Demo,L=Utrecht,C=NL