
federated-corda-node:

  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: corda-k8s # Replace with the resource group of the Azure Kubernetes cluster

  service:
    type: LoadBalancer
    loadBalancerIP: 20.31.101.154 # Replace with pre-instantiated Azure Public IP Address

  p2pPort: 10005
  rpcPort: 10006
  p2pAddress: 20.31.101.154

  myLegalName: OU=Node1,O=Demo,L=Utrecht,C=NL

  dataFetcherType: codognotto
  dataFetcherGetEndpointUrl: https://fenix-codognotto.azurewebsites.net/api/GetOrderEvent/90/2023/192
  dataFetcherRmlEndpointUrl: https://translate.lab.semantic-treehouse.nl/api/18

federated-node-api:

  configmap:
    federated:
      node:
        event:
          distribution:
            rules:
              list: static
              static:
                destinations: OU=Node2,O=Demo,L=Utrecht,C=NL
