
corda-node:
  myLegalName: OU=BDI,O=Codognotto,L=Salgareda,C=IT

  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: corda-k8s # Replace with the resource group of the Azure Kubernetes cluster

  service:
    type: LoadBalancer
    loadBalancerIP: 20.31.101.154 # Replace with pre-instantiated Azure Public IP Address

  p2pAddress: 20.31.101.154

corda-client-api:
  configmap:
    bdi:
      event:
        distribution:
          rules:
            list: static
            static:
              # Comma separated list of static destinations, all events will be sent to the locations specified here.
              destinations: DCA/Schiphol/NL