{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "corda-client-api.fullname" $ }}-config
data:
  application.properties: |-
    # This file allows for defining additional events types.
    # ArrivalEvent and LoadEvent are built-in events, they can be used out of the box.
    # They must be specified here in addition to any custom events as shown in the example below
    # if they are going to be used.
    #federated.node.event.types[0].eventType=custom.event.type.v1
    #federated.node.event.types[0].rml=file:/opt/api/config/CustomEventType.ttl
{{ end -}}