apiVersion: v1
kind: Service
metadata:
  name: {{ template "corda-node.fullname" . }}
  labels: {{ include "corda-node.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPort }}
      protocol: TCP
      name: rpc
  selector:
    app.kubernetes.io/name: {{ template "corda-node.fullname" $ }}-corda
    app.kubernetes.io/instance: {{ .Release.Name }}
