{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secrets.name }}
  labels: {{ include "corda-node.labels" . | nindent 4 }}
data:
{{ template "secretfile" (dict "name" "network-truststore.jks" "config" .Values.secrets.networkTrustStore "Files" .Files )}}
{{- end }}