
annotations: {}
  # service.beta.kubernetes.io/azure-load-balancer-resource-group: corda-k8s # Example annotation for automatic load-balancer

service:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1 # Default value that shouldn't work. Follow instructions in main chart file.
  p2pPort: 10005
  rpcPort: 10006

graphdb:
  enabled: true
  host: namespace-graphdb
  port: 7200
  privateRepository: private
  repository: federated-shacl

image: corda/corda-zulu-java1.8-4.5.8:latest
nodeConf: |-
  devMode=true
  myLegalName="O=EMONS,L=Groningen,C=NL,OU=TNO"
  p2pAddress="replaceloadBalancerIPhere:10005"
  rpcSettings {
      address="0.0.0.0:10006"
      adminAddress="0.0.0.0:10046"
  }
  security {
      authService {
          dataSource {
              type=INMEMORY
              users=[
                  {
                      password=vzzuABeCut3jGoJfEp94
                      permissions=[
                          ALL
                      ]
                      user=user1
                  }
              ]
          }
      }
  }
  devModeOptions.allowCompatibilityZone=true
  compatibilityZoneURL="https://nms.basicdatasharinginfrastructure.net"
secrets:
  create: true
  name: corda-secrets
  networkTrustStore:
    base64: /u3+7QAAAAIAAAADAAAAAgAKbmV0d29ya21hcAAAAYEapmlOAAVYLjUwOQAAAnswggJ3MIICEqADAgECAgheMqTvTkzqQDAUBggqhkjOPQQDAgYIKoZIzj0DAQcwgYMxCzAJBgNVBAYTAkdCMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjEbMBkGA1UECgwSQ29yZGl0ZSBGb3VuZGF0aW9uMSMwIQYDVQQLDBpDb3JkaXRlIEZvdW5kYXRpb24gTmV0d29yazEQMA4GA1UEAwwHUm9vdCBDQTAeFw0yMjAzMjIwMDAwMDBaFw0zMjAzMTkwMDAwMDBaMFExCzAJBgNVBAYTAkdCMQ8wDQYDVQQHEwZMb25kb24xGzAZBgNVBAoTEkNvcmRpdGUgRm91bmRhdGlvbjEUMBIGA1UEAxMLTmV0d29yayBNYXAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASvSfauQtuRqQJq5/UFiWleKG9RyLQ+uJQhfJp0FUne/74eVN1ewmZ7+GFZM9RKkypwxFjfoPNTqXQeIYFq0DfGo4GWMIGTMB0GA1UdDgQWBBQ2KkBC8D+pS3+vpIrZzwpdaheuATAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIHgDAjBgNVHSUEHDAaBggrBgEFBQcDAQYIKwYBBQUHAwIGBFUdJQAwHwYDVR0jBBgwFoAUIv5I5mVFORB/aF5lh4HNYyMtl6cwEQYKKwYBBAGDimIBAQQDAgECMBQGCCqGSM49BAMCBggqhkjOPQMBBwNJADBGAiEA5EiPMBRw7FDho0U3byJjZ2NxG6hJxE/SxajnPw3rYksCIQDttpzo7glpbrKiBPVEBX+vofadYKTXYjSAwiRWZatlsQAAAAIAE2NvcmRhaW50ZXJtZWRpYXRlY2EAAAGBGqZpTgAFWC41MDkAAAKxMIICrTCCAkigAwIBAgIIPMZejI6VysUwFAYIKoZIzj0EAwIGCCqGSM49AwEHMIGDMQswCQYDVQQGEwJHQjEPMA0GA1UECAwGTG9uZG9uMQ8wDQYDVQQHDAZMb25kb24xGzAZBgNVBAoMEkNvcmRpdGUgRm91bmRhdGlvbjEjMCEGA1UECwwaQ29yZGl0ZSBGb3VuZGF0aW9uIE5ldHdvcmsxEDAOBgNVBAMMB1Jvb3QgQ0EwHhcNMjIwMzIyMDAwMDAwWhcNMzIwMzE5MDAwMDAwWjCBgzELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMRswGQYDVQQKDBJDb3JkaXRlIEZvdW5kYXRpb24xIzAhBgNVBAsMGkNvcmRpdGUgRm91bmRhdGlvbiBOZXR3b3JrMRAwDgYDVQQDDAdEb29ybWFuMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGB2VU4BtJuesJPsffqvQcgR8ZjFHJvkHImzRGq8mh5BfKrp+tbuo8tQsRKUY9LQCMTRqeH5PYdFJVqq6LZm5nqOBmTCBljAdBgNVHQ4EFgQU1uevbLESzvvdS64b3qToGvuTyn8wDwYDVR0TAQH/BAUwAwEB/zALBgNVHQ8EBAMCAYYwIwYDVR0lBBwwGgYIKwYBBQUHAwEGCCsGAQUFBwMCBgRVHSUAMB8GA1UdIwQYMBaAFCL+SOZlRTkQf2heZYeBzWMjLZenMBEGCisGAQQBg4piAQEEAwIBATAUBggqhkjOPQQDAgYIKoZIzj0DAQcDSQAwRgIhAKjXEKXqi8PDUEc08XJ3VugYvcMo4UOMResG0PPvpxVYAiEAuE6dKRuLZm4EENRlSY+dPaAx142HGRPNepwHBslNSTcAAAACAAtjb3JkYXJvb3RjYQAAAYEapmlOAAVYLjUwOQAAAp0wggKZMIICNaADAgECAghouvj/zEiMbDAUBggqhkjOPQQDAgYIKoZIzj0DAQcwgYMxCzAJBgNVBAYTAkdCMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjEbMBkGA1UECgwSQ29yZGl0ZSBGb3VuZGF0aW9uMSMwIQYDVQQLDBpDb3JkaXRlIEZvdW5kYXRpb24gTmV0d29yazEQMA4GA1UEAwwHUm9vdCBDQTAeFw0yMjAzMjIwMDAwMDBaFw0zMjAzMTkwMDAwMDBaMIGDMQswCQYDVQQGEwJHQjEPMA0GA1UECAwGTG9uZG9uMQ8wDQYDVQQHDAZMb25kb24xGzAZBgNVBAoMEkNvcmRpdGUgRm91bmRhdGlvbjEjMCEGA1UECwwaQ29yZGl0ZSBGb3VuZGF0aW9uIE5ldHdvcmsxEDAOBgNVBAMMB1Jvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQv566NBfnZaxg2zUJg6lhAFWouoeKdAe0pUMwSjuDxnHB1G2b4F5aUKp5yttci5575GW7MmE97hRfpHTCNDFxQo4GGMIGDMB0GA1UdDgQWBBQi/kjmZUU5EH9oXmWHgc1jIy2XpzAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBhjAjBgNVHSUEHDAaBggrBgEFBQcDAQYIKwYBBQUHAwIGBFUdJQAwHwYDVR0jBBgwFoAUIv5I5mVFORB/aF5lh4HNYyMtl6cwFAYIKoZIzj0EAwIGCCqGSM49AwEHA0gAMEUCIEIFiadE8N16yoNNeamHP7hu6Y0YsV/dfQICTBvK9ksHAiEA1UsykmkohWDVylicQotI4zj/OQZE5LowX020P0/TFAc4+v770QlrSxGcCF/1tEwqkppnyw==