apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "graphdb.fullname" $ }}-graphdb
  labels: {{ include "graphdb.labels" $ | nindent 4 }}
spec:
  serviceName:  {{ template "graphdb.fullname" . }}
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: {{ template "graphdb.fullname" $ }}-persist-pv
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi  
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "graphdb.fullname" $ }}-graphdb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "graphdb.fullname" $ }}-graphdb
        app.kubernetes.io/instance: {{ .Release.Name }}
      containers:      
      - name: graphdb
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 7200
            protocol: TCP
            name: rpc
        volumeMounts:
          - mountPath: "/opt/graphdb"
            name: {{ template "graphdb.fullname" $ }}-persist-pv
