{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb.fullname" . }}
  labels:
    {{- include "graphdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphdb.selectorLabels" . | nindent 4 }}

{{ end -}}